<html>
<title>Handicrafts</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="//cdn.shopify.com/s/files/1/1078/6412/t/13/assets/main.css?2067156536209426619" rel="stylesheet" type="text/css" media="all" />
    <link href="//cdn.shopify.com/s/files/1/1078/6412/t/13/assets/plugins.css?2067156536209426619" rel="stylesheet" type="text/css" media="all" />  
 
  
  <link href="//cdn.shopify.com/s/files/1/1078/6412/t/13/assets/bazien.css?2067156536209426619" rel="stylesheet" type="text/css" media="all" />
  <link href="//cdn.shopify.com/s/files/1/1078/6412/t/13/assets/responsive.css?2067156536209426619" rel="stylesheet" type="text/css" media="all" />
  
 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
    .dropbtn {
        width:195%;
        height:6%;
    background-color: #16A085;
    color: white;
    
    font-size: 16px;
    border: none;
}


.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
   
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #16A085;
}

    .newspaper {
    -webkit-column-count: 3; /* Chrome, Safari, Opera */
    -moz-column-count: 3; /* Firefox */
    column-count: 3;
    }
body {font-family: "Lato", sans-serif}
.mySlides {display: none}



</style>

<body>
    <script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

    <script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>



<!-- Sidebar on click -->
<nav class="w3-sidebar w3-bar-block w3-white w3-card w3-animate-left w3-xxlarge" style="display:none;z-index:2" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-display-topright w3-text-teal">Close
    <i class="fa fa-remove"></i>
  </a>
  <a href="#" class="w3-bar-item w3-button">Link 1</a>
  <a href="#" class="w3-bar-item w3-button">Link 2</a>
  <a href="#" class="w3-bar-item w3-button">Link 3</a>
  <a href="#" class="w3-bar-item w3-button">Link 4</a>
  <a href="#" class="w3-bar-item w3-button">Link 5</a>
</nav>

<!-- Navbar -->
<div class="w3-top">
 <div class="w3-bar  w3-left-align w3-white">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  <a href="/" class="w3-bar-item"><p><font size="6" style="color: #C71585;">Zodhpur</font></p></a>
  <a href="/" class="w3-bar-item w3-button w3-hide-small w3-hover-white"><font size="4">Home</font></a>
  <a href="/index/about/" class="w3-bar-item w3-button w3-hide-small w3-hover-white"><font size="4">About Us</font></a>
  
  <a href="/index/contact/" class="w3-bar-item w3-button w3-hide-small w3-hover-white"><font size="4">Contact us</font></a>
    <div class="w3-dropdown-hover w3-hide-small">
        <button class="w3-button" title="Notifications"><font size="4">My Account </font><i class="fa fa-caret-down"></i></button>     
    <div class="w3-dropdown-content w3-card-4 w3-bar-block">
      <a href="/users/signup/" class="w3-bar-item w3-button">Sign Up</a>
      <a href="/users/login/" class="w3-bar-item w3-button">Login</a>
      
    </div>
  </div>
   <a href="#" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-teal" title="Search"><i class="fa fa-search"></i></a>
 </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium">
    <a href="#team" class="w3-bar-item w3-button">Team</a>
    <a href="#work" class="w3-bar-item w3-button">Work</a>
    <a href="#pricing" class="w3-bar-item w3-button">Price</a>
    <a href="/index/contact/" class="w3-bar-item w3-button">Contact</a>
    <a href="#" class="w3-bar-item w3-button">Search</a>
  </div>
</div>


<br>
<br>
<br>
<br>
<br>

<!--main content-->
    <div class="main container">
      <!--<div class="row columns-layout"-->
        <div class="col-main col-sm-9 col-sm-push-3">
          <div class="header-background-default">
            <div class="header-content-title">
              <h1>Products</h1>
            </div>
            
            
          </div>

          

          <div class="category-products">
            <div class="toolbar">
              <div class="sorter">
                <div class="sort-by">
                  
                    
                      
                      <div class="dropdown">                  
                      <button class="btn btn-primary dropdown-toggle"  style="background-color: #DC7633" type="button" data-toggle="dropdown">sort By
    <span class="caret"></span></button>
                    <ul class="dropdown-menu" width="100%">
      <li><a href="#">Low To High</a></li>
      <li><a href="#">High To Low</a></li>
      
    </ul>
  </div>

                    <div class="dropdown">                  
                      <button class="btn btn-primary dropdown-toggle"  style="background-color: #DC7633" type="button" data-toggle="dropdown">Material
    <span class="caret"></span></button>
                    <ul class="dropdown-menu" width="100%">
      <li><a href="#">Low To High</a></li>
      <li><a href="#">High To Low</a></li>
      
    </ul>
  </div>
                  
                  
                </div>
               
               
              </div>
            </div>
            
            <div id="products-viewmode" class="row products-grid">
              
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6 item" style="margin-left:5%; ">
                <div class="item-product-image-box">
  
  <a class="product-image" href="/products/paper/" title="Toys And Things ">
    <div class="product-img-additional back">
      <img src="/img/download.jpg"  href=" /products/paper/" alt="">
   	<!-- To handle image size - Authored by Rohan Arora on 12th Dec, 2016 -->
    </div>
  </a>
  
</div>
<h3 class="product-name">
    <a href="/products/paper/" title=""><font size="2"><b>Toys And Things</b></font></a>
</h3>



<div class="price-box">
  
  
  
  <p class="special-price"><span class="price"><span class=money>$45.49</span></span></p>
  
  
  
</div>
                    <center> <a href="/products/paper/">   <button Type="button" name="" style="width:70%;align:center; height:7%; background-color: #5499C7;">Add To Cart</button></center>
                </div>
              
                &nbsp;&nbsp;&nbsp;&nbsp;
                
                
                
                
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6 item" style="margin-left:22%;">
                <div class="item-product-image-box" >
  
  <a class="product-image" href="/products/ipic000002" title="">
    <div class="product-img-additional back">
      <img src="a1.jpg" style="width:65%;" alt="Rusticity Aromatherapy Incense Stick & Cone gift set - 40 Sticks & 20 Cones | Handmade | (8in)">
   	<!-- To handle image size - Authored by Rohan Arora on 12th Dec, 2016 -->
    </div>
  </a>
 
</div>
<h3 class="product-name">
  <a href="/products/ipic000002" title="Rusticity Aromatherapy Incense Stick & Cone gift set - 40 Sticks & 20 Cones | Handmade | (8in)">Toys And Things</a>
</h3>


<div class="hidden-class">
  <div class="desc std">
    Fragrances, they say, have a power of persuasion stronger than that of words, appearances, emotions, or will. The persuasive power of an odor cannot be fended off, it enters into...
    <a href="/products/ipic000002" title="Rusticity Aromatherapy Incense Stick & Cone gift set - 40 Sticks & 20 Cones | Handmade | (8in)" class="link-learn">Learn More</a>
  </div>
</div>

<div class="review-wrap">
  <span class="shopify-product-reviews-badge" data-id="9005688515"></span>
</div>
<div class="price-box">
  
  
  
  <span class="regular-price"><span class="price"><span class=money>$16.49</span></span></span>
  
  
  
</div>

                     <a href="https:\\www.amazon.com">   <button Type="button" name="" style="width:70%; height:7%; background-color: #5499C7;">Add To Cart</button>
                </div>
              
                
            </div>
           </div>
        </div>
        
      
      
      <!-- collection side bar-->
    

<div class="col-left sidebar col-sm-3 col-sm-pull-9">
  <div class="col-left sidebar">
    
    <div id="sidebar-nav" class="block sidebar-nav-left  left-categories">
      <div class="block-title">
        <span>COLLECTIONS</span>
      </div>
      
<div class="dropdown">
  <button class="dropbtn">Women</button>
  <div class="dropdown-content" style="margin-top:50%; height:250%; width:200%;">
    <a href="/products/wcd/">Dresses / Kurtas</a>
      </div>
</div>
  <br>
  <br> <br>
  
  
  <div class="dropdown">
  <button class="dropbtn" style="width:270%">Men</button>
  <div class="dropdown-content"style="margin-top:63%; width:280%;" >
    <a href="/products/paper/">Decorative Boxes</a>
     <a href="/products/paper/">Key Hangers</a>
      <a href="/products/paper/">Clipboard & Paper Holders </a>
       <a href="/products/paper/">Stationery Holders</a>
        <a href="/products/paper/">Indoor Games</a>
         <a href="/products/paper/">Coffee Table Book & Map</a>
      </div>
</div>

  <br>
  <br> <br>
  
  
  <div class="dropdown">
  <button class="dropbtn" style="width:185%">Children</button>
  <div class="dropdown-content" style="margin-top:40%; width:200%;">
    <a href="/products/paper/">Piggy Banks</a>
     <a href="/products/paper/">Toys & Games</a>
          </div>
</div>

  
  <br>
  <br> <br>
  
  
  <div class="dropdown">
  <button class="dropbtn" style="width:145%">Home Utility</button>
  <div class="dropdown-content" style="margin-top:30%; width:180%;">
    <a href="/products/trays/">Trays & Things</a>
     <a href="/products/paper/">Serving Ware</a>
     <a href="/products/candlestand/">Candle Holders</a>
          </div>
</div>
  
  <br>
  <br> <br>
  
  
  <div class="dropdown">
  <button class="dropbtn" style="width:230%">Decor</button>
  <div class="dropdown-content" style="margin-top:40%; width:240%;">
    <a href="/products/paper/">Puppets</a>
     <a href="/products/door1/">Door Decor</a>
     <a href="/products/walldecor/">Wall Hanging</a>
          </div>
</div>

  <br>
  <br> <br>
  
  
  <div class="dropdown">
  <button class="dropbtn" style="width:130%">Office Product</button>
  <div class="dropdown-content" style="margin-top:28%; width:135%;">
    <a href="/products/trays/">Decorative Boxes</a>
          </div>
</div>

 </div>
    </div>
 </div>
</div>
<!-- Footer -->
<footer class="w3-container w3-padding-32 w3-text-grey" style="background-color:#DCDCDC;">
    
    <center> <div class="logo-ft">
                    <img src="" />
                  </div>
                  <p class="text-center">Zodhpur is an international brand of traditional products handcrafted to complement your modern living style. We bring to you items of utility while giving your home the dash of rustic that you’ve been looking for.</p>

  <h4>Follow Us</h4>
  <a class="w3-button w3-large w3-teal " href="https://www.facebook.com/" title="Facebook"><i class="fa fa-facebook"></i></a>
  <a class="w3-button w3-large  w3-teal" href="#" title="Twitter"><i style="border-radius:50%" class="fa fa-twitter"></i></a>
  <a class="w3-button w3-large  w3-teal w3-hide-small" href="#" title="Linkedin"><i class="fa fa-linkedin"></i></a>
  <p>Powered by <a href="#" target="_blank"></p>

  <div style="position:relative;bottom:100px;z-index:1;" class="w3-tooltip w3-right">
    <span class="w3-text w3-padding w3-teal w3-hide-small">Go To Top</span>   
    <a class="w3-button w3-theme" href="#myPage"><span class="w3-xlarge">
    <i class="fa fa-chevron-circle-up"></i></span></a>
  </div>
  </center>
    <div class="w3-container  w3-row-padding w3-center w3-margin-top w3-margin-right" style="margin-top:10px; ">
        <div class="w3-third ">
            <p align="left"><h3>Navigation</h3>
            <p>
                <a href="/">Home</a><br>
                <a href="/index/about/">About Us</a><br>
                <a href="/index/contact/">Contact Us</a>
                
            </p>
        
        </div>


<div class="w3-third" ailgn="left">
    <p align="left"><h3>Collection</h3>
            <p>
                <a href="/products/wcd/"> Women </a> <br>
                <a href="/products/wcd/"> Men  </a>  <br>
                <a href="/products/wcd/"> Children</a><br>
                <a href="/products/paper/"> Home Utility</a><br>
                <a href="/products/walldecor/"> Decor</a><br>
                <a href="/products/paper/"> Work</a>
                
</p>
</p>
        </div>
        
<div class="w3-third">
    <p align="left"> <h3>Popular</h3>
           <p>
               <a href="/products/kitchen/">   Kitchen</a><br>
               <a href="/products/game/">   Games</a></br>
    <a href="">  Office</a>
                
            </p>
</p>
        </div>
        

 </div>
  </footer>
<script>
    //automatic slide show
    var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 4000);    
}

// Script for side navigation
function w3_open() {
    var x = document.getElementById("mySidebar");
    x.style.width = "300px";
    x.style.paddingTop = "10%";
    x.style.display = "block";
}

// Close side navigation
function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else { 
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>
</body>
</html>